Controllers/HomeController.cs
using CST_350_Minesweeper.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Milestone.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Milestone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

using CST_350_Minesweeper.Models;
using CST_350_Minesweeper.Services;
using Milestone.Controllers;

namespace login.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessLogin(User user)
        {
            LoginService loginService = new LoginService();
            
            if (loginService.IsValid(user))
            {
                User currentUser = loginService.GetCurrentLoggedInUser();
                var minesweeperBoardController = new MinesweeperBoardController();

                return RedirectToAction("Index", "Game");

            }
            else
            {
                return View("LoginFailure", user);
            }
        }
    }
}

Controllers/RegisterAccountController.cs
using CST_350_Minesweeper.Models;
using CST_350_Minesweeper.Services;
using Microsoft.AspNetCore.Mvc;

namespace CST_350_Minesweeper.Controllers
{
    public class RegisterAccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessRegisterUser(User user)
        {
            RegisterService service= new RegisterService();
            if (!service.IsValid(user))
                return View("RegisterFailure", user);
            else
            {
                return View("RegisterSuccess", user);
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="main_menu">
    <div class="text-center">
        <h1 class="display-4">MINESWEEPER</h1>
    </div>
    <div class="menu_container">
        <div class="game_menu">
            <div class="text-center">
                <h4>Main Menu</h4>
            </div>
            <div>
                <ul id="menu"> 
                    <li id="menu_item">
                        <a id="menu_item-text" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                    </li>
                    <li id="menu_item">
                        <a id="menu_item-text" asp-area="" asp-controller="RegisterAccount" asp-action="Index">Regester</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>    
</div>